### PR TITLE
Support FileField and ImageField serialization to links

### PR DESCRIPTION
**Pull request by webjunkie**
This renders file and image fields into links as well:

```json
{
    "_links": {
        "self": {
            "href": "http://testserver/file-resources/1/"
        },
        "file": {
            "href": "http://testserver/file-resources/1/foo_ZQBLrGA"
        },
        "image": {
            "href": "http://testserver/file-resources/1/image_FOyklJw"
        }
    }
}
```

### CODE REVIEW

**Comment by jstaffans** [comment]
can this support the optional `title` link attribute as well?

**Comment by webjunkie** [comment]
Is that in the master already? I'd want to keep it separate from this change here.

I'm thinking we could do some field (like you already started to work on) that can be configure to add a title:

```python
Serializer:
    file_title = ContributeTitleField(to='file', model_field='file_title')
```

**Comment by jstaffans** [comment]
I just want to make sure that there is a path forward to support titles.

**Comment by webjunkie** [comment]
Support for titles is in #13

**Pull request merged**
