### PR TITLE
Limit _links to only Hal* fields

### LINKED ISSUE #22: SlugRelatedField gets put into links
SlugRelatedField is never a http link, so it might not be useful to end up there.

### PR DESCRIPTION
**Pull request by claytondaley**
Fixes #22.  Issue #22 specifically addressed the case where a `SlugRelatedField` was included in `_links` even thought it was a non-URL slug (like `name`).  When investigating this problem, it became clear that `HalModelSerializer` was making overly broad assumptions about the link-ness of stock DRF serializers.

For example, `test_filefield_serialization` verifies that a serialized `FileField` is put into `_links`.  While this is often the case, the [documentation](http://www.django-rest-framework.org/api-guide/fields/#filefield) states that `FileField` only returns a URL if `use_url` is true (and a `name` otherwise).  

Since it's valid to include a link in the body (but invalid to include a non-link in `_links`), this PR switches to the hyper-conservative assumption that only `Hal*` fields should be included in `_links`.  

 - Tests with non-`Hal*` fields were edited to use compliant `Hal*` fields.  
 - The `FileField` test case was left failing (I believe rightly so) as the basis of a broader discussion.  
 - Fields like `HyperlinkedIdentityField` need discussed.  On the one hand, a user can easily replace them with `HalHyperlinkedIdentityField` to move them to `_links`.  On the other, it's always a hyperlink.  Is there a use-case where it generates a link, but doesn't belong in `_links`?  Obviously, I have defaulted to the "safe" case, but don't object adding some additional fields if we're confident that they're safe.

To assist in writing the PR, the test suite was upgraded:

 - A case for the SlugRelatedField was added
 - Several tests were converted to check keys explicitly rather than count the length of a dict -- an unreliable way to check dict composition.
 - Temporary files built by the test cases have been relocated to `./tmp` for simpler cleanup (and possible `.gitignore`)

### CODE REVIEW

**Comment by claytondaley** [comment]
OK.  This fixes #22, but has surfaced a really odd interaction between `serializer_related_field` and individual field-level serializers for related objects.  I'm going to add a tests case to illustrate the conflict.

**Comment by webjunkie** [comment]
This looks good and useful! Can you fix the tests? Thanks.

**Comment by claytondaley** [comment]
By "fix the tests", do you agree that `FileField` (by default) should not be placed in links (so that test should be removed)?

Do you have feelings about `HyperlinkedIdentityField`?  Are we OK going ultra-conservative (i.e. accepting this PR) and revisiting the discussion later?  Worst case, the PR forces a user to convert these fields to `HalHyperlinkedIdentityField` (already exists).

**Comment by webjunkie** [comment]
> The FileField test case was left failing (I believe rightly so) as the basis of a broader discussion.

Sorry, I only really read this now 😇 

> Is there a use-case where it generates a link, but doesn't belong in _links? 

The way I see it, if it's a download file link, a web resource or something not specifically related to API navigation, it does not have to be in `_links`. So using only `Hal*` fields would give a user some leverage on that. So it makes sense to remove `FileField` from links. So the same goes for `HyperlinkedIdentityField`. In our main use of this Hal library here, we already only use `HalHyperlinkedIdentityField`, so that should be fine.

**Comment by claytondaley** [comment]
There ya go.

**Comment by claytondaley** [comment]
Good catch.  I started cleaning it up, but a key example (Contributing optional properties to links directly) depends on the `FileField` assumption assumption.  It takes more than a cursory edit since the content may need replaced.

**Comment by claytondaley** [comment]
Getting sample code working motivated a more invasive change:

 - Added `HalIncludeInLinksMixin` as a generic way to flag serializers that should be included in links
     - Refactored the relevant `Hal*` classes to use the mixin
     - Changed the searializer to look for this class
 - Added `HalFileField` so the current example could remain otherwise unchanged
     - Also directed users to it as a minimal example of how to create new `_links` fields
 - Added a test case so we'll be notified if the (current) README example ever stops working

**Comment by jstaffans** [comment]
Can you solve the merge conflicts, then this should be ready to go as well.

**Pull request merged**
